#{% set privateSettingsDest = "/data/mineinabyss/server-config-private" %}#
global:
  files:
    plugins/Geary:
      deleteUntracked: true
      keep:
        - config.yml
        - resourcepack.zip
feat/mobs:
  copyPaths:
    - source: plugins/Geary/prefabs/mineinabyss/mobs
      dest: plugins/Geary/prefabs/mineinabyss/mobs
    - source: plugins/Geary/spawns
      dest: plugins/Geary/spawns
    - source: plugins/Geary/spawning.yml
      dest: plugins/Geary/
    - source: plugins/MythicMobs
      dest: plugins/MythicMobs
    - source: .servers/disable_mythic_examples
      dest: plugins/MythicMobs
  files:
    plugins/MythicMobs:
      deleteUntracked: true
      keep:
        - config/
        - data/
        - stats.yml
feat/emotes:
  copyPaths:
    - source: plugins/Emojy
      dest: plugins/Emojy
  files:
    plugins/Emojy:
      deleteUntracked: true
      keep:
        - gifs/ # Image sequences get generated in here
        - fonts/
        - pack.zip
feat/blocks:
  copyPaths:
    - source: plugins/Blocky
      dest: plugins/Blocky
    - source: plugins/Geary/prefabs/mineinabyss/blocks
      dest: plugins/Geary/prefabs/mineinabyss/blocks

feat/chat:
  copyPaths:
    - source: plugins/Chatty
      dest: plugins/Chatty

feat/cosmetics:
  copyPaths:
    - source: mc-resourcepacks/cosmetics
      dest: plugins/Geary/template_pack
    - source: plugins/Geary/prefabs/cosmetics
      dest: plugins/Geary/prefabs/cosmetics
    - source: mc-resourcepacks/cosmetics
      dest: plugins/Packy/resourcepacks/cosmetics

feat/bosses:
  copyPaths:
    - source: "{{ privateSettingsDest }}/plugins/MythicMobs/packs/bosses"
      dest: plugins/MythicMobs/packs/bosses

feat/loot_chests:
  copyPaths:
    - source: plugins/Geary/prefabs/mia-loot
      dest: plugins/Geary/prefabs/mia-loot

feat/items:
  copyPaths:
    - source: plugins/Geary/prefabs/mineinabyss/items
      dest: plugins/Geary/prefabs/mineinabyss/items
    - source: plugins/Geary/prefabs/minecraft/recipes
      dest: plugins/Geary/prefabs/minecraft/recipes
    - source: mc-resourcepacks/items
      dest: plugins/Geary/template_pack
    - source: mc-resourcepacks/tools_2d
      dest: plugins/Packy/resourcepacks/tools_2d
    - source: mc-resourcepacks/tools_3d
      dest: plugins/Packy/resourcepacks/tools_3d
    - source: mc-resourcepacks/armor_new
      dest: plugins/Packy/resourcepacks/armor_new
    - source: mc-resourcepacks/armor_old
      dest: plugins/Packy/resourcepacks/armor_old

feat/hud:
  copyPaths:
      - source: plugins/MythicHUD
        dest: plugins/MythicHUD

feat/pets:
  copyPaths:
    - source: plugins/MythicMobs/packs/pets
      dest: plugins/MythicMobs/packs/pets
    - source: plugins/MCPets
      dest: plugins/MCPets

feat/delvers:
  copyPaths:
    - source: plugins/MythicMobs/packs/delvers
      dest: plugins/MythicMobs/packs/delvers

feat/hiddenore:
  copyPaths:
    - source: plugins/HiddenOre
      dest: plugins/HiddenOre

feat/ost:
  copyPaths:
    - source: "{{ privateSettingsDest }}/mc-resourcepacks/ost"
      dest: plugins/Packy/resourcepacks/ost
    - source: mc-datapacks/music_discs
      dest: worlds/world/datapacks/music_discs

feat/deeperworld:
  copyPaths:
    - source: mc-datapacks/deeper_world
      dest: worlds/world/datapacks/deeper_world

feat/resourcepack-common:
  copyPaths:
    - source: mc-resourcepacks/common
      dest: plugins/Packy/resourcepacks/common

# Servers
minecraft:
  copyPaths: [ .servers/minecraft ]
  variables:
    env:
      PRIVATE_PLUGINS_TOKEN: "{{ PRIVATE_PLUGINS_TOKEN | default('') }}"
      PACKY_ACCESS_TOKEN: "{{ PACKY_ACCESS_TOKEN | default('') }}"
      SERVER_NAME: "{{ SERVER_NAME | default('') }}"
      PACKY_PUBLIC_ADDRESS: "{{ PACKY_PUBLIC_ADDRESS | default('') }}"
      DISCORD_BOT_TOKEN: "{{ DISCORD_BOT_TOKEN | default('') }}"
    velocity_forward_secret: "{{ VELOCITY_FORWARDING_SECRET  | default('') }}"
  include:
    - feat/chat
    - feat/emotes
    - feat/resourcepack-common
    - feat/deeperworld

survival:
  copyPaths: [ .servers/survival ]
  variables:
    chatty:
      enableHover: true
      serverPrefix: ":survival:"
  include:
    - minecraft
    - feat/items
    - feat/loot_chests
    - feat/cosmetics
    - feat/blocks
    - feat/mobs
    - feat/hud
    - feat/hiddenore
    - feat/ost

build:
  variables:
    chatty:
      enableHover: true
      serverPrefix: ":build:"
      localChatRadius: 0
  copyPaths: [ .servers/build ]
  include:
    - minecraft
    - feat/blocks
    - feat/items
    - feat/loot_chests
    - feat/cosmetics

staging:
  copyPaths: [ ] # Staging should mimic another server as closely as possible, use `include` below instead
  variables:
    chatty:
      enableHover: true
      serverPrefix: ":survival::test:"
      localChatRadius: 0
  include:
    - survival

dev:
  copyPaths: [ .servers/dev ]
  variables:
    chatty:
      serverPrefix: ":test:"
      localChatRadius: 0
  include:
    - minecraft
    - feat/blocks
    - feat/items
    - feat/loot_chests
    - feat/cosmetics
    - feat/mobs
    - feat/pets
    - feat/delvers
    - feat/bosses
    - feat/hud
    - feat/ost

dev-alpha:
  copyPaths: [ .servers/dev-alpha ]
  include:
    - dev

# Used for local development, where as few plugins as possible are auto downloaded
dev-basic:
  include:
    - dev

archive:
  copyPaths: [ .servers/archive ]
  variables:
    chatty:
      serverPrefix: ":adventure:"
      localChatRadius: 0
  include:
    - minecraft

# Proxy
velocity:
  copyPaths: [ .servers/proxy ]
  variables:
    velocityForwardingSecret: "{{ VELOCITY_FORWARDING_SECRET | default('') }}"
    spicord:
      token: "{{ SPICORD_TOKEN }}"
  include: [ ]
