- name:
  hosts: localhost
  connection: local
  vars:
    server_name: "{{ lookup('env', 'SERVER_NAME') }}"
    minecraft_uid: "{{ lookup('env', 'UID', '1000') }}"
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
  vars_files:
    - "servers/servers.yml"

  roles:
    - role: bbmodels
      when: "'minecraft' in servers[server_name]"

    - role: configs
