- name:
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    server_name: "{{ lookup('env', 'SERVER_NAME') }}"
    minecraft_uid: "{{ lookup('env', 'UID', '1000') }}"
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
  vars_files:
    - "variables.yml"
  pre_tasks:
    - include_vars:
        file: "keepup/configs.yml"
        name: "servers"

  roles:
    - role: bbmodels

    - role: configs
