# TODO replace secrets
- name: "Copy from {{ src }} to destination"
  synchronize:
    src: "{{ src }}"
    dest: "{{ home }}"
    archive: false
    recursive: true
    checksum: true
    group: false
    owner: false
    perms: false
  register: files

- name: Listing files copied
  debug: var=files.stdout_lines
  when: files.changed
