- name: Ensure directory structure exists
  file:
    path: '{{ home }}/{{ dir.path }}'
    state: directory
  with_filetree: '{{ templates_source }}'
  when: dir.state == 'directory'
  loop_control:
    loop_var: dir
    label: "{{ dir.path }}"

- name: Ensure files are populated from templates
  template:
    src: '{{ template.src }}'
    dest: '{{ home }}/{{ template.path | regex_replace(".j2$", "") }}'
  with_filetree: '{{ templates_source }}'
  when: template.state == 'file'
  loop_control:
    loop_var: template
    label: "{{ template.path }}"
